jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          # cache: npm
          
      - name: Setup EAS 
        uses: expo/expo-github-action@8.2.1
        
        with:
          eas-version: latest
          token: ${{ secrets.EXPOTOKEN }}
          packager: npm

      
      - name: Install dependencies
        working-directory: ./react-native-app
        run: npm install
      
      - name: Build app
        working-directory: ./react-native-app
        run: eas build --platform android --profile production 
